version: "3.9"  # optional since v1.27.0
services:
  FileUP:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
      - logvolume01:/var/log
    links:
      - redis
  DataBase:
    image: docker pull mcr.microsoft.com/mssql/server
volumes:
  logvolume01: {